# Site settings
title: Joost Gadellaa
description: 'Business Card Page'
url: 'http://joostgadellaa.nl'
baseurl: ''
profilepic: '/images/joostgadellaa.jpeg'
bkimage: '/images/DSC_6093.jpeg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Joost Gadellaa'
  email: website@joostgadellaa.nl
#  twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username:  joostgadellaa
  linkedin_username:  joostgadellaa
#  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md']
